# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("model_type", models.CharField(max_length=50)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("training_samples", models.IntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=list)),
                ("use_cases", models.JSONField(blank=True, default=list)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time"),
                            ("subscription", "Subscription"),
                            ("per_inference", "Per Inference"),
                            ("free", "Free"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("downloads", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_models",
                        to="marketplace.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "marketplace model",
                "verbose_name_plural": "marketplace models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("removed", "Removed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("deployed_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_deployments",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_deployments",
                        to="core.company",
                    ),
                ),
                (
                    "marketplace_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="marketplace.marketplacemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "deployment",
                "verbose_name_plural": "deployments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_reviews",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "marketplace_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.marketplacemodel",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_reviews",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketplacemodel",
            index=models.Index(
                fields=["category", "is_active"], name="marketplace_categor_41ffd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacemodel",
            index=models.Index(
                fields=["pricing_type"], name="marketplace_pricing_4c0220_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacemodel",
            index=models.Index(
                fields=["is_featured"], name="marketplace_is_feat_19a712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["marketplace_model", "consortium"],
                name="marketplace_marketp_094f54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["deployed_by"], name="marketplace_deploye_05b9e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(fields=["status"], name="marketplace_status_375063_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["marketplace_model", "rating"],
                name="marketplace_marketp_beb166_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("marketplace_model", "reviewer")},
        ),
    ]
