# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deployment",
            options={
                "ordering": ["-deployed_at"],
                "verbose_name": "deployment",
                "verbose_name_plural": "deployments",
            },
        ),
        migrations.RenameIndex(
            model_name="deployment",
            new_name="marketplace_consort_23f729_idx",
            old_name="mkt_deploy_cons_idx",
        ),
        migrations.RenameIndex(
            model_name="deployment",
            new_name="marketplace_status_375063_idx",
            old_name="mkt_deploy_status_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacemodel",
            new_name="marketplace_categor_1c95cb_idx",
            old_name="mkt_model_category_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacemodel",
            new_name="marketplace_model_t_688b4b_idx",
            old_name="mkt_model_type_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacemodel",
            new_name="marketplace_is_acti_9513c3_idx",
            old_name="mkt_model_active_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacemodel",
            new_name="marketplace_is_feat_19a712_idx",
            old_name="mkt_model_featured_idx",
        ),
        migrations.RenameIndex(
            model_name="marketplacemodel",
            new_name="marketplace_downloa_e9ec1a_idx",
            old_name="mkt_model_downloads_idx",
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="marketplace_marketp_c375cd_idx",
            old_name="mkt_review_model_idx",
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="marketplace_rating_c67539_idx",
            old_name="mkt_review_rating_idx",
        ),
    ]
