# Generated by Django 5.2.10 on 2026-01-26 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(blank=True, default='direct', max_length=50)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'sandbox lead',
                'verbose_name_plural': 'sandbox leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sandboxtemplate',
            options={'ordering': ['name'], 'verbose_name': 'sandbox template', 'verbose_name_plural': 'sandbox templates'},
        ),
        migrations.RenameIndex(
            model_name='experiment',
            new_name='sandbox_exp_sandbox_abe0b5_idx',
            old_name='exp_sandbox_idx',
        ),
        migrations.RenameIndex(
            model_name='experiment',
            new_name='sandbox_exp_status_b9eacc_idx',
            old_name='exp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='experiment',
            new_name='sandbox_exp_experim_bf728f_idx',
            old_name='exp_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='sandbox_san_owner_i_2133ee_idx',
            old_name='sb_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='sandbox_san_status_483b7e_idx',
            old_name='sb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='sandbox_san_expires_e235a9_idx',
            old_name='sb_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='syntheticdataset',
            new_name='sandbox_syn_sandbox_3cc090_idx',
            old_name='sd_sandbox_idx',
        ),
        migrations.RenameIndex(
            model_name='syntheticdataset',
            new_name='sandbox_syn_dataset_3300c5_idx',
            old_name='sd_type_idx',
        ),
        migrations.AddField(
            model_name='sandboxlead',
            name='converted_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sandboxlead',
            index=models.Index(fields=['email'], name='sandbox_san_email_d47d33_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxlead',
            index=models.Index(fields=['token'], name='sandbox_san_token_5e36db_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxlead',
            index=models.Index(fields=['created_at'], name='sandbox_san_created_99338c_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxlead',
            index=models.Index(fields=['converted'], name='sandbox_san_convert_d79971_idx'),
        ),
    ]
