# Generated by Django 5.2.10 on 2026-01-26 14:55
# Cleaned: SandboxLead creation, indexes, and RenameIndex ops moved to 0001_initial/0003.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandboxtemplate',
            options={
                'ordering': ['name'],
                'verbose_name': 'sandbox template',
                'verbose_name_plural': 'sandbox templates',
            },
        ),
        # All RenameIndex and SandboxLead operations handled by 0001 + 0003.
    ]
