# Generated by Django 5.2.12 on 2026-03-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0002_add_sandbox_lead"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dataupload",
            new_name="sandbox_dat_company_068bab_idx",
            old_name="sandbox_du_company_idx",
        ),
        migrations.RenameIndex(
            model_name="dataupload",
            new_name="sandbox_dat_created_5ebc02_idx",
            old_name="sandbox_du_created_idx",
        ),
        migrations.RenameIndex(
            model_name="experiment",
            new_name="sandbox_exp_sandbox_abe0b5_idx",
            old_name="sandbox_exp_sandbox_idx",
        ),
        migrations.RenameIndex(
            model_name="experiment",
            new_name="sandbox_exp_status_b9eacc_idx",
            old_name="sandbox_exp_status_idx",
        ),
        migrations.RenameIndex(
            model_name="experiment",
            new_name="sandbox_exp_experim_bf728f_idx",
            old_name="sandbox_exp_type_idx",
        ),
        migrations.RenameIndex(
            model_name="sandbox",
            new_name="sandbox_san_owner_i_2133ee_idx",
            old_name="sandbox_sb_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="sandbox",
            new_name="sandbox_san_status_483b7e_idx",
            old_name="sandbox_sb_status_idx",
        ),
        migrations.RenameIndex(
            model_name="sandbox",
            new_name="sandbox_san_expires_e235a9_idx",
            old_name="sandbox_sb_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="sandbox_sub_status_730163_idx",
            old_name="sandbox_sub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="sandbox_sub_plan_5c112f_idx",
            old_name="sandbox_sub_plan_idx",
        ),
        migrations.RenameIndex(
            model_name="syntheticdataset",
            new_name="sandbox_syn_sandbox_3cc090_idx",
            old_name="sandbox_sd_sandbox_idx",
        ),
        migrations.RenameIndex(
            model_name="syntheticdataset",
            new_name="sandbox_syn_dataset_3300c5_idx",
            old_name="sandbox_sd_dtype_idx",
        ),
    ]
