# Generated by Django 5.2.12 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_rename_sandbox_du_company_idx_sandbox_dat_company_068bab_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sandboxlead',
            new_name='sandbox_san_email_d47d33_idx',
            old_name='sandbox_sbl_email_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxlead',
            new_name='sandbox_san_token_5e36db_idx',
            old_name='sandbox_sbl_token_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxlead',
            new_name='sandbox_san_created_99338c_idx',
            old_name='sandbox_sbl_created_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxlead',
            new_name='sandbox_san_convert_d79971_idx',
            old_name='sandbox_sbl_conv_idx',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='trialing', max_length=20),
        ),
    ]
