# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureImportance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=255)),
                (
                    "importance_score",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("importance_rank", models.IntegerField()),
                (
                    "computation_method",
                    models.CharField(
                        choices=[
                            ("permutation", "Permutation"),
                            ("shap", "SHAP"),
                            ("gain", "Gain"),
                            ("split", "Split"),
                            ("correlation", "Correlation"),
                        ],
                        default="permutation",
                        max_length=20,
                    ),
                ),
                (
                    "std_deviation",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "feature importance",
                "verbose_name_plural": "feature importances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("drift", "Drift"),
                            ("performance", "Performance"),
                            ("fairness", "Fairness"),
                            ("feature", "Feature"),
                            ("data_quality", "Data Quality"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "model insight",
                "verbose_name_plural": "model insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExplanationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "explanation_type",
                    models.CharField(
                        choices=[
                            ("feature_importance", "Feature Importance"),
                            ("shap", "SHAP"),
                            ("lime", "LIME"),
                            ("counterfactual", "Counterfactual"),
                            ("partial_dependence", "Partial Dependence"),
                            ("anchor", "Anchor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("prediction_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("explanation", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation_requests",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "explanation request",
                "verbose_name_plural": "explanation requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
