# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
        ("core", "0004_company_trial_fields"),
        ("explainability", "0001_initial"),
        ("federated", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="explanationrequest",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="explanation_requests",
                to="federated.federatedmodel",
            ),
        ),
        migrations.AddField(
            model_name="explanationrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanation_requests",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="featureimportance",
            name="consortium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_importances",
                to="consortiums.consortium",
            ),
        ),
        migrations.AddField(
            model_name="featureimportance",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feature_importances",
                to="federated.federatedmodel",
            ),
        ),
        migrations.AddField(
            model_name="modelinsight",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelinsight",
            name="consortium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_insights",
                to="consortiums.consortium",
            ),
        ),
        migrations.AddIndex(
            model_name="explanationrequest",
            index=models.Index(
                fields=["consortium", "status"], name="explainabil_consort_34b49b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="explanationrequest",
            index=models.Index(
                fields=["requester"], name="explainabil_request_68f402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureimportance",
            index=models.Index(
                fields=["consortium", "model"], name="explainabil_consort_bdaf94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureimportance",
            index=models.Index(
                fields=["importance_rank"], name="explainabil_importa_674eba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelinsight",
            index=models.Index(
                fields=["consortium", "insight_type"],
                name="explainabil_consort_ba55f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelinsight",
            index=models.Index(
                fields=["severity", "is_active"], name="explainabil_severit_154ad1_idx"
            ),
        ),
    ]
