# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explainability", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="explanationrequest",
            new_name="explainabil_consort_a73af3_idx",
            old_name="expl_req_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="explanationrequest",
            new_name="explainabil_request_68f402_idx",
            old_name="expl_req_requester_idx",
        ),
        migrations.RenameIndex(
            model_name="explanationrequest",
            new_name="explainabil_status_d70af1_idx",
            old_name="expl_req_status_idx",
        ),
        migrations.RenameIndex(
            model_name="featureimportance",
            new_name="explainabil_consort_bfc2cb_idx",
            old_name="feat_imp_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="featureimportance",
            new_name="explainabil_importa_674eba_idx",
            old_name="feat_imp_rank_idx",
        ),
        migrations.RenameIndex(
            model_name="modelinsight",
            new_name="explainabil_consort_8ecfc7_idx",
            old_name="insight_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="modelinsight",
            new_name="explainabil_insight_4f7637_idx",
            old_name="insight_type_idx",
        ),
        migrations.RenameIndex(
            model_name="modelinsight",
            new_name="explainabil_severit_8ebf08_idx",
            old_name="insight_severity_idx",
        ),
    ]
