# Generated by Django 5.2.12 on 2026-03-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0002_initial'),
        ('models', '0005_add_tiers_webhooks_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationrequest',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explanation_requests', to='models.mlmodel'),
        ),
        migrations.AlterField(
            model_name='featureimportance',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_importances', to='models.mlmodel'),
        ),
    ]
