# Generated by Django 5.2.12 on 2026-03-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0003_alter_explanationrequest_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureimportance',
            options={'ordering': ['importance_rank'], 'verbose_name': 'feature importance', 'verbose_name_plural': 'feature importances'},
        ),
    ]
