# Generated by Django 5.2.12 on 2026-03-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0004_fix_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationrequest',
            name='explanation_type',
            field=models.CharField(choices=[('feature_importance', 'Feature Importance'), ('shap', 'SHAP'), ('lime', 'LIME'), ('counterfactual', 'Counterfactual'), ('partial_dependence', 'Partial Dependence'), ('anchor', 'Anchor'), ('decision_path', 'Decision Path'), ('summary', 'Summary')], max_length=30),
        ),
    ]
