# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("add_member", "Add Member"),
                            ("remove_member", "Remove Member"),
                            ("change_model", "Change Model"),
                            ("change_params", "Change Parameters"),
                            ("distribute_rewards", "Distribute Rewards"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("passed", "Passed"),
                            ("rejected", "Rejected"),
                            ("executed", "Executed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("yes_votes", models.IntegerField(default=0)),
                ("no_votes", models.IntegerField(default=0)),
                (
                    "voting_weight_yes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "voting_weight_no",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "proposal",
                "verbose_name_plural": "proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(default="ETH", max_length=10)),
                ("distributions", models.JSONField(default=list)),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_distributions",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "reward distribution",
                "verbose_name_plural": "reward distributions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "support",
                    models.CharField(
                        choices=[
                            ("for", "For"),
                            ("against", "Against"),
                            ("abstain", "Abstain"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                ("comment", models.TextField(blank=True)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="governance.proposal",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("proposal_created", "Proposal Created"),
                            ("proposal_executed", "Proposal Executed"),
                            ("proposal_cancelled", "Proposal Cancelled"),
                            ("vote_cast", "Vote Cast"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("reward_distributed", "Reward Distributed"),
                            ("config_changed", "Config Changed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("previous_hash", models.CharField(blank=True, max_length=66)),
                ("event_hash", models.CharField(blank=True, max_length=66)),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "event_type"],
                        name="governance__consort_316569_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="governance__actor_i_3ad488_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["consortium", "status"], name="governance__consort_38c1ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["proposer"], name="governance__propose_215838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewarddistribution",
            index=models.Index(
                fields=["consortium"], name="governance__consort_a94d83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["proposal", "support"], name="governance__proposa_a48825_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("proposal", "voter")},
        ),
    ]
