# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={
                "ordering": ["-voted_at"],
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
            },
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="governance__consort_316569_idx",
            old_name="gov_audit_cons_type_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="governance__consort_efcd05_idx",
            old_name="gov_audit_cons_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="governance__event_h_0a8d04_idx",
            old_name="gov_audit_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="proposal",
            new_name="governance__consort_38c1ca_idx",
            old_name="gov_prop_cons_status_idx",
        ),
        migrations.RenameIndex(
            model_name="proposal",
            new_name="governance__expires_834ea9_idx",
            old_name="gov_prop_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="rewarddistribution",
            new_name="governance__consort_a94d83_idx",
            old_name="gov_reward_cons_idx",
        ),
        migrations.RenameIndex(
            model_name="rewarddistribution",
            new_name="governance__distrib_d4288f_idx",
            old_name="gov_reward_dist_idx",
        ),
        migrations.RenameIndex(
            model_name="vote",
            new_name="governance__proposa_81d99e_idx",
            old_name="gov_vote_proposal_idx",
        ),
        migrations.RenameIndex(
            model_name="vote",
            new_name="governance__voter_i_e659b3_idx",
            old_name="gov_vote_voter_idx",
        ),
    ]
