# Generated by Django 5.2.12 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('proposal_created', 'Proposal Created'), ('proposal_executed', 'Proposal Executed'), ('proposal_cancelled', 'Proposal Cancelled'), ('vote_cast', 'Vote Cast'), ('member_added', 'Member Added'), ('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('reward_distributed', 'Reward Distributed'), ('config_changed', 'Config Changed'), ('consortium_created', 'Consortium Created')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('add_member', 'Add Member'), ('remove_member', 'Remove Member'), ('change_model', 'Change Model'), ('change_params', 'Change Parameters'), ('start_training', 'Start Training'), ('distribute_rewards', 'Distribute Rewards'), ('update_config', 'Update Config'), ('dissolve', 'Dissolve'), ('custom', 'Custom')], max_length=30),
        ),
    ]
