# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="core_apikey_key_has_967bbc_idx",
            old_name="core_apikey_key_has_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="core_apikey_company_28c0ae_idx",
            old_name="core_apikey_company_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="core_apikey_is_acti_697a96_idx",
            old_name="core_apikey_is_acti_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_action_d9fb24_idx",
            old_name="core_auditl_action_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_resourc_19ae0b_idx",
            old_name="core_auditl_resourc_m4n5o6_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_created_dc23ea_idx",
            old_name="core_auditl_created_p7q8r9_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_company_094942_idx",
            old_name="core_auditl_company_s0t1u2_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="core_compan_email_511913_idx",
            old_name="core_compan_email_9b1c8a_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="core_compan_is_acti_f26725_idx",
            old_name="core_compan_is_acti_5e0b7a_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="core_user_email_38052c_idx",
            old_name="core_user_email_8d7e1a_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="core_user_company_1ff1de_idx",
            old_name="core_user_company_3f4b2c_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
