# Generated by Django 5.2.10 on 2026-01-27 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_apikey_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("api_requests", models.IntegerField(default=0)),
                ("predictions", models.IntegerField(default=0)),
                ("training_runs", models.IntegerField(default=0)),
                ("data_uploads_bytes", models.BigIntegerField(default=0)),
                ("rate_limit_hits", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "usage tracking",
                "verbose_name_plural": "usage tracking",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("secret", models.CharField(max_length=255)),
                ("events", models.JSONField(default=list)),
                ("custom_headers", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("max_retries", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=30)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "webhook",
                "verbose_name_plural": "webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("event_id", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="custom_daily_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="custom_rate_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["tier"], name="core_compan_tier_3262c2_idx"),
        ),
        migrations.AddField(
            model_name="usagetracking",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_tracking",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="core.webhook",
            ),
        ),
        migrations.AddIndex(
            model_name="usagetracking",
            index=models.Index(
                fields=["company", "date"], name="core_usaget_company_b36c26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagetracking",
            index=models.Index(fields=["date"], name="core_usaget_date_6b8f5e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usagetracking",
            unique_together={("company", "date")},
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["company"], name="core_webhoo_company_0d2229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["is_active"], name="core_webhoo_is_acti_8f6ae4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook"], name="core_webhoo_webhook_386b64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["event_type"], name="core_webhoo_event_t_4c9320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["status"], name="core_webhoo_status_538322_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["next_retry_at"], name="core_webhoo_next_re_e5f0a8_idx"
            ),
        ),
    ]
