# Generated by Django 5.2.11 on 2026-03-02 23:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_apikey_created_by_and_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="secret",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
