# Generated by Django 5.2.12 on 2026-03-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_company_trial_fields"),
        ("core", "0006_encrypt_webhook_secret"),
    ]

    operations = []
