# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryBenchmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("industry", models.CharField(db_index=True, max_length=100)),
                ("sub_industry", models.CharField(blank=True, max_length=100)),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("accuracy", "Accuracy"),
                            ("latency", "Latency"),
                            ("cost", "Cost"),
                            ("throughput", "Throughput"),
                            ("privacy_score", "Privacy Score"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "p10_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "p25_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "p50_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "p75_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "p90_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("sample_size", models.IntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "industry benchmark",
                "verbose_name_plural": "industry benchmarks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["industry", "metric_name"],
                        name="competitive_industr_cc8c6d_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="competitive_period__738bff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompetitiveReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("opportunities", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitive_reports",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "competitive report",
                "verbose_name_plural": "competitive reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "industry"],
                        name="competitive_company_6c093e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="competitive_status_21da4d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "percentile_rank",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitive_metrics",
                        to="core.company",
                    ),
                ),
                (
                    "benchmark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_metrics",
                        to="competitive_insights.industrybenchmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "company metric",
                "verbose_name_plural": "company metrics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "metric_name"],
                        name="competitive_company_417bca_idx",
                    ),
                    models.Index(
                        fields=["benchmark"], name="competitive_benchma_9693ae_idx"
                    ),
                ],
            },
        ),
    ]
