# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitive_insights", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companymetric",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "company metric",
                "verbose_name_plural": "company metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="industrybenchmark",
            options={
                "ordering": ["-period_start"],
                "verbose_name": "industry benchmark",
                "verbose_name_plural": "industry benchmarks",
            },
        ),
        migrations.RenameIndex(
            model_name="companymetric",
            new_name="competitive_company_b92e0f_idx",
            old_name="ci_metric_company_idx",
        ),
        migrations.RenameIndex(
            model_name="companymetric",
            new_name="competitive_metric__dbd9f2_idx",
            old_name="ci_metric_name_idx",
        ),
        migrations.RenameIndex(
            model_name="companymetric",
            new_name="competitive_period__043431_idx",
            old_name="ci_metric_period_idx",
        ),
        migrations.RenameIndex(
            model_name="industrybenchmark",
            new_name="competitive_industr_3aa0d3_idx",
            old_name="ci_bench_industry_idx",
        ),
        migrations.RenameIndex(
            model_name="industrybenchmark",
            new_name="competitive_metric__d427da_idx",
            old_name="ci_bench_metric_idx",
        ),
        migrations.RenameIndex(
            model_name="industrybenchmark",
            new_name="competitive_period__738bff_idx",
            old_name="ci_bench_period_idx",
        ),
    ]
