# Generated by Django 5.2.12 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitivereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='generating', max_length=20),
        ),
    ]
