# Generated by Django 5.2.12 on 2026-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_insights', '0002_alter_competitivereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitivereport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
