# Generated by Django 5.2.12 on 2026-03-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitive_insights', '0003_fix_model_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industrybenchmark',
            unique_together={('industry', 'metric_name', 'period_start')},
        ),
    ]
