# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consortiums", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consortiuminvitation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "consortium invitation",
                "verbose_name_plural": "consortium invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="consortiummember",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "consortium member",
                "verbose_name_plural": "consortium members",
            },
        ),
        migrations.RenameIndex(
            model_name="consortium",
            new_name="consortiums_status_ec613f_idx",
            old_name="consort_status_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="consortium",
            new_name="consortiums_owner_i_d5a83f_idx",
            old_name="consort_owner_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="consortium",
            new_name="consortiums_created_5ea42b_idx",
            old_name="consort_created_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="consortiuminvitation",
            new_name="consortiums_invitee_c1513e_idx",
            old_name="invite_email_idx",
        ),
        migrations.RenameIndex(
            model_name="consortiuminvitation",
            new_name="consortiums_status_017da4_idx",
            old_name="invite_status_idx",
        ),
        migrations.RenameIndex(
            model_name="consortiummember",
            new_name="consortiums_consort_db2bb0_idx",
            old_name="consort_mem_cons_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="consortiummember",
            new_name="consortiums_company_8ad660_idx",
            old_name="consort_mem_company_idx",
        ),
        migrations.RenameIndex(
            model_name="contributionproof",
            new_name="consortiums_consort_e229db_idx",
            old_name="contrib_cons_comp_idx",
        ),
        migrations.RenameIndex(
            model_name="contributionproof",
            new_name="consortiums_data_ha_93f341_idx",
            old_name="contrib_data_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="contributionproof",
            new_name="consortiums_verifie_fd8320_idx",
            old_name="contrib_verified_idx",
        ),
    ]
