# Generated by Django 5.2.10 on 2026-01-29 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consortiums", "0002_alter_consortiuminvitation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionproof",
            name="blockchain_registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributionproof",
            name="schema_version",
            field=models.CharField(default="1.0", max_length=20),
        ),
        migrations.AddField(
            model_name="contributionproof",
            name="verification_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contributionproof",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TrainingResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("model_hash", models.CharField(blank=True, max_length=64)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("loss", models.FloatField(blank=True, null=True)),
                ("epochs_completed", models.IntegerField(default=0)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("contributions_count", models.IntegerField(default=0)),
                ("total_records", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                (
                    "blockchain_registered_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_results",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "training result",
                "verbose_name_plural": "training results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "status"],
                        name="consortiums_consort_71d81a_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="consortiums_task_id_b6fa2f_idx"
                    ),
                ],
            },
        ),
    ]
