# Generated by Django 5.2.10 on 2026-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consortiums", "0003_add_verification_training_blockchain_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consortiuminvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consortiummember",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("rejected", "Rejected"),
                    ("left", "Left"),
                    ("removed", "Removed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
