# Generated by Django 5.2.12 on 2026-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consortiums", "0004_alter_consortiuminvitation_status_and_more"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consortiummember",
            name="unique_consortium_company",
        ),
        migrations.AlterField(
            model_name="consortium",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("linear_regression", "Linear Regression"),
                    ("logistic_regression", "Logistic Regression"),
                    ("decision_tree", "Decision Tree"),
                    ("kmeans", "K-Means Clustering"),
                ],
                default="logistic_regression",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="consortium",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("training", "Training"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consortiummember",
            unique_together={("consortium", "company")},
        ),
    ]
