# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("model_type", models.CharField(max_length=50)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("training", "Training"),
                            ("ready", "Ready"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federated_models",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "federated model",
                "verbose_name_plural": "federated models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EdgeNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("gpu", "GPU"),
                            ("cpu", "CPU"),
                            ("tpu", "TPU"),
                            ("fpga", "FPGA"),
                        ],
                        default="cpu",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edge_nodes",
                        to="core.company",
                    ),
                ),
                (
                    "deployed_models",
                    models.ManyToManyField(
                        blank=True,
                        related_name="edge_nodes",
                        to="federated.federatedmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "edge node",
                "verbose_name_plural": "edge nodes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InferenceEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("rest", "REST"),
                            ("grpc", "gRPC"),
                            ("websocket", "WebSocket"),
                            ("batch", "Batch"),
                        ],
                        default="rest",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("request_count", models.IntegerField(default=0)),
                ("total_latency_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_endpoints",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_endpoints",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_endpoints",
                        to="federated.federatedmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "inference endpoint",
                "verbose_name_plural": "inference endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InferenceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("input_hash", models.CharField(blank=True, max_length=66)),
                ("encryption_key_id", models.CharField(blank=True, max_length=255)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="federated.inferenceendpoint",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_requests",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "inference request",
                "verbose_name_plural": "inference requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InferenceResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_output", models.TextField(blank=True)),
                ("output_metadata", models.JSONField(blank=True, default=dict)),
                ("confidence_scores", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="federated.inferencerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "inference result",
                "verbose_name_plural": "inference results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="federatedmodel",
            index=models.Index(
                fields=["consortium", "status"], name="federated_f_consort_f04cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edgenode",
            index=models.Index(
                fields=["company", "status"], name="federated_e_company_e4bd5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceendpoint",
            index=models.Index(
                fields=["consortium", "status"], name="federated_i_consort_922851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceendpoint",
            index=models.Index(
                fields=["company"], name="federated_i_company_281627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inferencerequest",
            index=models.Index(
                fields=["endpoint", "status"], name="federated_i_endpoin_eb5546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inferencerequest",
            index=models.Index(
                fields=["requester"], name="federated_i_request_c4d403_idx"
            ),
        ),
    ]
