# Generated by Django 5.2.12 on 2026-03-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgenode',
            name='node_type',
            field=models.CharField(choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('tpu', 'TPU'), ('fpga', 'FPGA'), ('cloud', 'Cloud'), ('on_premise', 'On Premise')], default='cpu', max_length=10),
        ),
        migrations.AlterField(
            model_name='inferenceendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('rest', 'REST'), ('grpc', 'gRPC'), ('websocket', 'WebSocket'), ('batch', 'Batch'), ('realtime', 'Realtime')], default='rest', max_length=20),
        ),
        migrations.AlterField(
            model_name='inferenceendpoint',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_endpoints', to='federated.federatedmodel'),
        ),
    ]
