# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("federated", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="edgenode",
            new_name="federated_e_company_25f208_idx",
            old_name="edge_company_idx",
        ),
        migrations.RenameIndex(
            model_name="edgenode",
            new_name="federated_e_status_da3dd6_idx",
            old_name="edge_status_idx",
        ),
        migrations.RenameIndex(
            model_name="federatedmodel",
            new_name="federated_f_consort_4929c2_idx",
            old_name="fed_model_cons_idx",
        ),
        migrations.RenameIndex(
            model_name="federatedmodel",
            new_name="federated_f_status_0c3d18_idx",
            old_name="fed_model_status_idx",
        ),
        migrations.RenameIndex(
            model_name="inferenceendpoint",
            new_name="federated_i_consort_657df9_idx",
            old_name="infer_ep_cons_idx",
        ),
        migrations.RenameIndex(
            model_name="inferenceendpoint",
            new_name="federated_i_company_281627_idx",
            old_name="infer_ep_company_idx",
        ),
        migrations.RenameIndex(
            model_name="inferenceendpoint",
            new_name="federated_i_status_fb04c9_idx",
            old_name="infer_ep_status_idx",
        ),
        migrations.RenameIndex(
            model_name="inferencerequest",
            new_name="federated_i_endpoin_1e94f9_idx",
            old_name="infer_req_ep_idx",
        ),
        migrations.RenameIndex(
            model_name="inferencerequest",
            new_name="federated_i_request_c4d403_idx",
            old_name="infer_req_req_idx",
        ),
        migrations.RenameIndex(
            model_name="inferencerequest",
            new_name="federated_i_status_a15e0d_idx",
            old_name="infer_req_status_idx",
        ),
    ]
