# Generated by Django 5.2.12 on 2026-03-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated', '0002_alter_edgenode_node_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatedmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('ready', 'Ready'), ('deployed', 'Deployed'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='inferenceendpoint',
            name='total_latency_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
