# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnsemblePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("n_samples", models.IntegerField(default=0)),
                ("prediction", models.JSONField(blank=True, default=list)),
                ("confidence", models.JSONField(blank=True, default=list)),
                ("model_predictions", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ensemble prediction",
                "verbose_name_plural": "ensemble predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ensemble",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "ensemble_type",
                    models.CharField(
                        choices=[
                            ("bagging", "Bagging"),
                            ("boosting", "Boosting"),
                            ("stacking", "Stacking"),
                            ("voting", "Voting"),
                            ("custom", "Custom"),
                        ],
                        default="voting",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("training", "Training"),
                            ("ready", "Ready"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("aggregation_config", models.JSONField(blank=True, default=dict)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "ensemble_improvement",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ensembles",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "ensemble",
                "verbose_name_plural": "ensembles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnsembleEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "recall",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "auc_roc",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "best_individual_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "improvement_over_best",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("test_samples", models.IntegerField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ensemble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="ensemble.ensemble",
                    ),
                ),
            ],
            options={
                "verbose_name": "ensemble evaluation",
                "verbose_name_plural": "ensemble evaluations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnsembleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=7),
                ),
                (
                    "individual_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "contribution_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ensemble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ensemble_models",
                        to="ensemble.ensemble",
                    ),
                ),
            ],
            options={
                "verbose_name": "ensemble model",
                "verbose_name_plural": "ensemble models",
                "ordering": ["-created_at"],
            },
        ),
    ]
