# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ensemble", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ensemble",
            new_name="ensemble_en_owner_i_4db11c_idx",
            old_name="ens_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="ensemble",
            new_name="ensemble_en_status_50ac89_idx",
            old_name="ens_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ensemblemodel",
            new_name="ensemble_en_ensembl_7847bc_idx",
            old_name="ensmodel_ensemble_idx",
        ),
        migrations.RenameIndex(
            model_name="ensemblemodel",
            new_name="ensemble_en_model_i_acc8b7_idx",
            old_name="ensmodel_model_idx",
        ),
        migrations.RenameIndex(
            model_name="ensembleprediction",
            new_name="ensemble_en_ensembl_cb98dc_idx",
            old_name="enspred_ensemble_idx",
        ),
        migrations.RenameIndex(
            model_name="ensembleprediction",
            new_name="ensemble_en_request_ae7862_idx",
            old_name="enspred_requester_idx",
        ),
        migrations.RenameIndex(
            model_name="ensembleprediction",
            new_name="ensemble_en_created_dd6492_idx",
            old_name="enspred_created_idx",
        ),
    ]
