# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ensemble", "0001_initial"),
        ("federated", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ensemblemodel",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ensemble_memberships",
                to="federated.federatedmodel",
            ),
        ),
        migrations.AddField(
            model_name="ensembleprediction",
            name="ensemble",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="ensemble.ensemble",
            ),
        ),
        migrations.AddIndex(
            model_name="ensemble",
            index=models.Index(
                fields=["owner", "status"], name="ensemble_en_owner_i_90a2c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ensembleevaluation",
            index=models.Index(
                fields=["ensemble"], name="ensemble_en_ensembl_ff7d8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ensemblemodel",
            index=models.Index(
                fields=["ensemble", "is_active"], name="ensemble_en_ensembl_a56a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ensembleprediction",
            index=models.Index(
                fields=["ensemble"], name="ensemble_en_ensembl_cb98dc_idx"
            ),
        ),
    ]
