# Generated by Django 5.2.12 on 2026-03-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260314_1324'),
        ('ensemble', '0002_initial'),
        ('models', '0005_add_tiers_webhooks_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensembleprediction',
            name='input_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='ensembleprediction',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensemble_predictions', to='core.company'),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='ensemble_type',
            field=models.CharField(choices=[('bagging', 'Bagging'), ('boosting', 'Boosting'), ('stacking', 'Stacking'), ('voting', 'Voting'), ('weighted', 'Weighted'), ('custom', 'Custom')], default='voting', max_length=20),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('training', 'Training'), ('ready', 'Ready'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ensemblemodel',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensemble_memberships', to='models.mlmodel'),
        ),
        migrations.AlterField(
            model_name='ensembleprediction',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ensembleprediction',
            name='prediction',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
