# Generated by Django 5.2.12 on 2026-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0003_ensembleprediction_input_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensembleevaluation',
            name='test_data_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
