# Generated by Django 5.2.12 on 2026-03-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0004_ensembleevaluation_test_data_hash'),
        ('models', '0005_add_tiers_webhooks_sharing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ensemblemodel',
            unique_together={('ensemble', 'model')},
        ),
    ]
