# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0005_initial"),
        ("core", "0004_company_trial_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_count", models.IntegerField(default=0)),
                ("feature_count", models.IntegerField(default=0)),
                ("null_count", models.IntegerField(default=0)),
                ("duplicate_count", models.IntegerField(default=0)),
                ("outlier_count", models.IntegerField(default=0)),
                ("schema_violations", models.IntegerField(default=0)),
                ("format_violations", models.IntegerField(default=0)),
                ("range_violations", models.IntegerField(default=0)),
                (
                    "completeness_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "consistency_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "timeliness_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_assessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_assessments",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_assessments",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_assessments",
                        to="consortiums.contributionproof",
                    ),
                ),
            ],
            options={
                "verbose_name": "quality assessment",
                "verbose_name_plural": "quality assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("completeness", "Completeness"),
                            ("range", "Range"),
                            ("format", "Format"),
                            ("uniqueness", "Uniqueness"),
                            ("referential", "Referential"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric", models.CharField(blank=True, max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal"),
                            ("ne", "Not Equal"),
                            ("between", "Between"),
                        ],
                        default="gt",
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_rules",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "quality rule",
                "verbose_name_plural": "quality rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("actual_value", models.CharField(blank=True, max_length=255)),
                ("expected_value", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_alerts",
                        to="core.company",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_quality_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="data_quality.qualityassessment",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="data_quality.qualityrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "quality alert",
                "verbose_name_plural": "quality alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qualityassessment",
            index=models.Index(
                fields=["consortium", "company"], name="data_qualit_consort_2d6cc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityassessment",
            index=models.Index(fields=["status"], name="data_qualit_status_563c30_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityrule",
            index=models.Index(
                fields=["consortium", "is_active"],
                name="data_qualit_consort_577fd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qualityrule",
            index=models.Index(
                fields=["rule_type"], name="data_qualit_rule_ty_120778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityalert",
            index=models.Index(
                fields=["rule", "status"], name="data_qualit_rule_id_cef434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityalert",
            index=models.Index(
                fields=["company"], name="data_qualit_company_767962_idx"
            ),
        ),
    ]
