# Generated by Django 5.2.12 on 2026-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityrule',
            name='rule_type',
            field=models.CharField(choices=[('completeness', 'Completeness'), ('range', 'Range'), ('format', 'Format'), ('uniqueness', 'Uniqueness'), ('referential', 'Referential'), ('threshold', 'Threshold'), ('custom', 'Custom')], max_length=20),
        ),
    ]
