# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="data_qualit_status_3323e3_idx",
            old_name="dq_alert_status_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityalert",
            new_name="data_qualit_company_767962_idx",
            old_name="dq_alert_company_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityassessment",
            new_name="data_qualit_consort_2d6cc3_idx",
            old_name="dq_assess_cons_comp_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityassessment",
            new_name="data_qualit_status_563c30_idx",
            old_name="dq_assess_status_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityassessment",
            new_name="data_qualit_overall_7aca3f_idx",
            old_name="dq_assess_score_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityrule",
            new_name="data_qualit_consort_475ccc_idx",
            old_name="dq_rule_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="qualityrule",
            new_name="data_qualit_is_acti_b312aa_idx",
            old_name="dq_rule_active_idx",
        ),
    ]
