# Generated by Django 5.2.12 on 2026-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0002_alter_qualityrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityrule',
            name='condition',
            field=models.JSONField(default=dict, help_text="Condition dict with 'operator' and 'value' keys, e.g. {'operator': '>=', 'value': 80}"),
        ),
    ]
