# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mlmodel",
            new_name="models_mlmo_model_t_9d75ba_idx",
            old_name="models_model_type_idx",
        ),
        migrations.RenameIndex(
            model_name="mlmodel",
            new_name="models_mlmo_status_de16a7_idx",
            old_name="models_status_idx",
        ),
        migrations.RenameIndex(
            model_name="mlmodel",
            new_name="models_mlmo_consort_374b32_idx",
            old_name="models_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="mlmodel",
            new_name="models_mlmo_owner_i_baf0ab_idx",
            old_name="models_owner_idx",
        ),
        migrations.RenameIndex(
            model_name="modelcheckpoint",
            new_name="models_mode_model_i_0530e9_idx",
            old_name="checkpoint_model_epoch_idx",
        ),
        migrations.RenameIndex(
            model_name="modelcheckpoint",
            new_name="models_mode_weights_71434d_idx",
            old_name="checkpoint_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="predictionlog",
            new_name="models_pred_model_i_31f693_idx",
            old_name="prediction_model_idx",
        ),
        migrations.RenameIndex(
            model_name="predictionlog",
            new_name="models_pred_request_40dd90_idx",
            old_name="prediction_requester_idx",
        ),
        migrations.RenameIndex(
            model_name="predictionlog",
            new_name="models_pred_timesta_8e44d1_idx",
            old_name="prediction_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="predictionlog",
            new_name="models_pred_encrypt_b63b4b_idx",
            old_name="prediction_encrypted_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingrun",
            new_name="models_trai_model_i_0f18a4_idx",
            old_name="training_model_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingrun",
            new_name="models_trai_status_60775c_idx",
            old_name="training_status_idx",
        ),
    ]
