# Generated by Django 5.2.10 on 2026-01-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models",
            "0002_rename_models_model_type_idx_models_mlmo_model_t_9d75ba_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("linear_regression", "Linear Regression"),
                    ("logistic_regression", "Logistic Regression"),
                    ("decision_tree", "Decision Tree"),
                    ("kmeans", "K-Means Clustering"),
                    ("random_forest", "Random Forest"),
                    ("gradient_boosting", "Gradient Boosting"),
                    ("ensemble_voting", "Ensemble Voting"),
                    ("neural_network", "Neural Network"),
                    ("svm", "Support Vector Machine"),
                    ("naive_bayes", "Naive Bayes"),
                    ("pca", "Principal Component Analysis"),
                    ("isolation_forest", "Isolation Forest"),
                    ("one_class_svm", "One-Class SVM"),
                    ("local_outlier_factor", "Local Outlier Factor"),
                    ("elliptic_envelope", "Elliptic Envelope"),
                    ("arima", "ARIMA"),
                    ("exponential_smoothing", "Exponential Smoothing"),
                    ("simple_moving_average", "Simple Moving Average"),
                    ("prophet_like", "Prophet-like Forecasting"),
                    ("ridge", "Ridge Regression"),
                    ("lasso", "Lasso Regression"),
                    ("elastic_net", "Elastic Net"),
                    ("ridge_classifier", "Ridge Classifier"),
                    ("sgd_regressor", "SGD Regressor"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
