# Generated by Django 5.2.10 on 2026-01-27 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_apikey_options_alter_company_options_and_more"),
        ("models", "0003_add_new_model_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="current_version",
            field=models.CharField(default="1.0.0", max_length=50),
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("major", models.IntegerField(default=1)),
                ("minor", models.IntegerField(default=0)),
                ("patch", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("params_snapshot", models.JSONField(default=dict)),
                ("config_snapshot", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("training_metrics", models.JSONField(default=dict)),
                ("changelog", models.TextField(blank=True)),
                ("release_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_versions",
                        to="core.company",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="models.mlmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "model version",
                "verbose_name_plural": "model versions",
                "ordering": ["-major", "-minor", "-patch"],
            },
        ),
        migrations.CreateModel(
            name="ModelExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("fheml_json", "FHE-ML JSON"),
                            ("fheml_binary", "FHE-ML Binary"),
                            ("onnx_compatible", "ONNX Compatible"),
                        ],
                        default="fheml_json",
                        max_length=20,
                    ),
                ),
                ("file_size_bytes", models.IntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("export_data", models.JSONField(default=dict)),
                ("include_weights", models.BooleanField(default=True)),
                ("include_config", models.BooleanField(default=True)),
                ("include_metadata", models.BooleanField(default=True)),
                ("encryption_key_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_exports",
                        to="core.company",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="models.mlmodel",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to="models.modelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "model export",
                "verbose_name_plural": "model exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchPredictionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("input_data", models.JSONField(default=list)),
                ("n_samples", models.IntegerField(default=0)),
                ("encrypted", models.BooleanField(default=False)),
                ("predictions", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                ("samples_processed", models.IntegerField(default=0)),
                ("progress_percent", models.FloatField(default=0.0)),
                ("total_latency_ms", models.FloatField(blank=True, null=True)),
                ("avg_latency_per_sample_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_jobs",
                        to="models.mlmodel",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_jobs",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "batch prediction job",
                "verbose_name_plural": "batch prediction jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model"], name="models_batc_model_i_1ce424_idx"
                    ),
                    models.Index(
                        fields=["requester"], name="models_batc_request_69df1b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="models_batc_status_56b65d_idx"
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="models_batc_priorit_daf1ae_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["model", "version"], name="models_mode_model_i_c92ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(fields=["status"], name="models_mode_status_bae3ba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together={("model", "version")},
        ),
        migrations.AddIndex(
            model_name="modelexport",
            index=models.Index(fields=["model"], name="models_mode_model_i_fe6420_idx"),
        ),
        migrations.AddIndex(
            model_name="modelexport",
            index=models.Index(fields=["format"], name="models_mode_format_8bbf4e_idx"),
        ),
        migrations.AddIndex(
            model_name="modelexport",
            index=models.Index(
                fields=["checksum_sha256"], name="models_mode_checksu_60f18e_idx"
            ),
        ),
    ]
