# Generated by Django 5.2.10 on 2026-01-27 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consortiums", "0002_alter_consortiuminvitation_options_and_more"),
        ("core", "0003_add_tiers_webhooks_sharing"),
        ("models", "0004_add_versioning_batch_export"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("full_access", "Full Access"),
                            ("prediction_only", "Prediction Only"),
                            ("read_only", "Read Only"),
                        ],
                        default="prediction_only",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "revenue_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("max_predictions", models.IntegerField(blank=True, null=True)),
                ("predictions_used", models.IntegerField(default=0)),
                ("terms", models.TextField(blank=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("request_message", models.TextField(blank=True)),
                ("approval_message", models.TextField(blank=True)),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares_approved",
                        to="core.company",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="models.mlmodel",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="models_shared",
                        to="core.company",
                    ),
                ),
                (
                    "source_consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_shares_given",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "target_consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_shares_received",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="models.modelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "model share",
                "verbose_name_plural": "model shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelShareRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_share_type",
                    models.CharField(
                        choices=[
                            ("full_access", "Full Access"),
                            ("prediction_only", "Prediction Only"),
                            ("read_only", "Read Only"),
                        ],
                        default="prediction_only",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "proposed_revenue_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_requests",
                        to="models.mlmodel",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_requests",
                        to="core.company",
                    ),
                ),
                (
                    "requesting_consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_share_requests",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "resulting_share",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_request",
                        to="models.modelshare",
                    ),
                ),
            ],
            options={
                "verbose_name": "model share request",
                "verbose_name_plural": "model share requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="modelshare",
            index=models.Index(fields=["model"], name="models_mode_model_i_8a36c2_idx"),
        ),
        migrations.AddIndex(
            model_name="modelshare",
            index=models.Index(
                fields=["source_consortium"], name="models_mode_source__ad6613_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelshare",
            index=models.Index(
                fields=["target_consortium"], name="models_mode_target__8f454e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelshare",
            index=models.Index(fields=["status"], name="models_mode_status_353157_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="modelshare",
            unique_together={("model", "target_consortium")},
        ),
        migrations.AddIndex(
            model_name="modelsharerequest",
            index=models.Index(fields=["model"], name="models_mode_model_i_8e3ea6_idx"),
        ),
        migrations.AddIndex(
            model_name="modelsharerequest",
            index=models.Index(
                fields=["requesting_consortium"], name="models_mode_request_df242e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelsharerequest",
            index=models.Index(fields=["status"], name="models_mode_status_a4336d_idx"),
        ),
    ]
