# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0004_alter_consortiuminvitation_status_and_more"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceFramework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("controls", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "compliance framework",
                "verbose_name_plural": "compliance frameworks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsortiumCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auto_check_interval",
                    models.IntegerField(
                        default=24,
                        help_text="Intervalo de verificación automática en horas.",
                    ),
                ),
                ("notification_emails", models.JSONField(blank=True, default=list)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_config",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "enabled_frameworks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consortium_configs",
                        to="compliance.complianceframework",
                    ),
                ),
            ],
            options={
                "verbose_name": "consortium compliance",
                "verbose_name_plural": "consortium compliances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("control_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partial", "Partial"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("warning", "Warning"),
                            ("skipped", "Skipped"),
                        ],
                        default="skipped",
                        max_length=20,
                    ),
                ),
                ("evidence", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_checks",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="compliance.complianceframework",
                    ),
                ),
            ],
            options={
                "verbose_name": "compliance check",
                "verbose_name_plural": "compliance checks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "framework"],
                        name="compliance__consort_64bc3f_idx",
                    ),
                    models.Index(
                        fields=["control_id"], name="compliance__control_0bbe82_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("control_id", models.CharField(blank=True, max_length=50)),
                ("attester_role", models.CharField(blank=True, max_length=100)),
                (
                    "attestation_type",
                    models.CharField(
                        choices=[
                            ("self_assessment", "Self Assessment"),
                            ("third_party", "Third Party"),
                            ("automated", "Automated"),
                        ],
                        default="self_assessment",
                        max_length=20,
                    ),
                ),
                ("statement", models.TextField()),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="compliance.complianceframework",
                    ),
                ),
            ],
            options={
                "verbose_name": "attestation",
                "verbose_name_plural": "attestations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "framework"],
                        name="compliance__consort_78ac1a_idx",
                    ),
                    models.Index(
                        fields=["attester"], name="compliance__atteste_e3c59f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("passed_controls", models.IntegerField(default=0)),
                ("failed_controls", models.IntegerField(default=0)),
                ("pending_controls", models.IntegerField(default=0)),
                ("total_controls", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_reports",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="compliance.complianceframework",
                    ),
                ),
            ],
            options={
                "verbose_name": "compliance report",
                "verbose_name_plural": "compliance reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "framework"],
                        name="compliance__consort_e11620_idx",
                    ),
                    models.Index(
                        fields=["status"], name="compliance__status_71e536_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataProcessingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processing_purpose", models.TextField()),
                ("data_categories", models.JSONField(default=list)),
                ("legal_basis", models.CharField(max_length=255)),
                ("data_subjects", models.TextField(blank=True)),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("retention_period", models.CharField(blank=True, max_length=100)),
                ("security_measures", models.TextField(blank=True)),
                ("cross_border_transfer", models.BooleanField(default=False)),
                ("transfer_safeguards", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_processing_records",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_processing_records",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "data processing record",
                "verbose_name_plural": "data processing records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consortium", "company"],
                        name="compliance__consort_e85195_idx",
                    )
                ],
            },
        ),
    ]
