# Generated by Django 5.2.10 on 2026-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complianceframework",
            options={
                "ordering": ["name"],
                "verbose_name": "compliance framework",
                "verbose_name_plural": "compliance frameworks",
            },
        ),
        migrations.AlterModelOptions(
            name="consortiumcompliance",
            options={
                "ordering": ["-last_check_at"],
                "verbose_name": "consortium compliance",
                "verbose_name_plural": "consortium compliance settings",
            },
        ),
        migrations.RenameIndex(
            model_name="attestation",
            new_name="compliance__consort_78ac1a_idx",
            old_name="attest_cons_fw_idx",
        ),
        migrations.RenameIndex(
            model_name="attestation",
            new_name="compliance__revoked_0af628_idx",
            old_name="attest_revoked_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancecheck",
            new_name="compliance__consort_64bc3f_idx",
            old_name="comp_check_cons_fw_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancecheck",
            new_name="compliance__control_0bbe82_idx",
            old_name="comp_check_control_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancecheck",
            new_name="compliance__status_42d71c_idx",
            old_name="comp_check_status_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancereport",
            new_name="compliance__consort_e11620_idx",
            old_name="comp_report_cons_fw_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancereport",
            new_name="compliance__status_71e536_idx",
            old_name="comp_report_status_idx",
        ),
        migrations.RenameIndex(
            model_name="dataprocessingrecord",
            new_name="compliance__consort_cc65df_idx",
            old_name="dpr_consortium_idx",
        ),
        migrations.RenameIndex(
            model_name="dataprocessingrecord",
            new_name="compliance__company_0088e3_idx",
            old_name="dpr_company_idx",
        ),
    ]
