# Generated by Django 5.2.12 on 2026-03-14 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortiums", "0004_alter_consortiuminvitation_status_and_more"),
        ("core", "0004_company_trial_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(db_index=True, max_length=66, unique=True),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("arbitrum-one", "Arbitrum One"),
                            ("arbitrum-sepolia", "Arbitrum Sepolia"),
                            ("ethereum-mainnet", "Ethereum Mainnet"),
                            ("ethereum-sepolia", "Ethereum Sepolia"),
                        ],
                        default="arbitrum-sepolia",
                        max_length=30,
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("deploy_contract", "Deploy Contract"),
                            ("register_model", "Register Model"),
                            ("submit_proof", "Submit Proof"),
                            ("governance_vote", "Governance Vote"),
                            ("reward_distribution", "Reward Distribution"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("reverted", "Reverted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("gas_price", models.BigIntegerField(blank=True, null=True)),
                ("value_wei", models.CharField(default="0", max_length=78)),
                ("from_address", models.CharField(max_length=42)),
                ("to_address", models.CharField(blank=True, max_length=42)),
                ("contract_address", models.CharField(blank=True, max_length=42)),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_transactions",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockchain_transactions",
                        to="consortiums.consortium",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartContractDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("governance", "Governance"),
                            ("model_registry", "Model Registry"),
                            ("computation_verifier", "Computation Verifier"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "address",
                    models.CharField(db_index=True, max_length=42, unique=True),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("arbitrum-one", "Arbitrum One"),
                            ("arbitrum-sepolia", "Arbitrum Sepolia"),
                            ("ethereum-mainnet", "Ethereum Mainnet"),
                            ("ethereum-sepolia", "Ethereum Sepolia"),
                        ],
                        default="arbitrum-sepolia",
                        max_length=30,
                    ),
                ),
                ("abi", models.JSONField(default=list)),
                ("bytecode_hash", models.CharField(blank=True, max_length=66)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contract_deployments",
                        to="core.company",
                    ),
                ),
                (
                    "consortium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_contract_deployments",
                        to="consortiums.consortium",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_deployments",
                        to="blockchain.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "smart contract deployment",
                "verbose_name_plural": "smart contract deployments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("block_number", models.BigIntegerField(db_index=True)),
                ("tx_hash", models.CharField(db_index=True, max_length=66)),
                ("args", models.JSONField(default=dict)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="blockchain.smartcontractdeployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "blockchain event",
                "verbose_name_plural": "blockchain events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contract", "event_name"],
                        name="blockchain__contrac_077516_idx",
                    ),
                    models.Index(
                        fields=["processed"], name="blockchain__process_c43e4e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["company", "status"], name="blockchain__company_c85031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["network", "block_number"],
                name="blockchain__network_9e66c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smartcontractdeployment",
            index=models.Index(
                fields=["company", "contract_type"],
                name="blockchain__company_eaab03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smartcontractdeployment",
            index=models.Index(
                fields=["network", "is_active"], name="blockchain__network_dd6e75_idx"
            ),
        ),
    ]
